# Generated by Django 4.0.6 on 2022-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bssignupdetail',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
