# Generated by Django 4.0.5 on 2022-08-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_mini', models.IntegerField(blank=True, null=True)),
                ('price_1', models.IntegerField(blank=True, null=True)),
                ('price_2', models.IntegerField(blank=True, null=True)),
                ('price_3', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='store/cake')),
                ('code', models.IntegerField(default=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
