# Generated by Django 4.0.5 on 2022-08-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_bssignupdetail_cake'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecake',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bssignupdetail'),
        ),
    ]
