# Generated by Django 4.0.5 on 2022-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField()),
                ('cakeImg', models.ImageField(upload_to='')),
                ('cakeSize', models.CharField(max_length=10)),
                ('cakeTaste', models.CharField(max_length=50)),
                ('addOptions', models.CharField(max_length=50)),
                ('cakeRequest', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'map',
            },
        ),
    ]
